# Generated by Django 5.1 on 2024-08-29 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snsapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='good',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='read',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='readname',
            field=models.TextField(blank=True, default=models.CharField(max_length=20), null=True),
        ),
    ]
