# Generated by Django 5.1 on 2024-08-29 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snsapp', '0002_alter_postmodel_good_alter_postmodel_read_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='readname',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
