# Generated by Django 5.1 on 2024-08-29 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snsapp', '0003_alter_postmodel_readname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='good',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='read',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
